name: Pull Request

on:
  pull_request:

env:
  DENO_VERSION: "v2.x"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 1

      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755  # v2.0.2
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Run Deno lint
        run: deno lint .